### ISSUE TITLE
Video recordings not displaying

### ISSUE THREAD

**Issue by roblandry** [linuxserver/docker-zoneminder#14]
Fix: 
apt-get install php7.0-gd
Modify php.ini allow php_gd2

Accomplished php.ini edit by symbolic link to php-config.ini

```
; custom configuration for php
; priority=10
date.timezone = America/New_York
extension=php_gd2.dll
```
Then in settings: 
disable random string appended for cache busting

My compose:
```
zoneminder:
    image: linuxserver/zoneminder
    container_name: zoneminder
    restart: always
    environment:
      - PHP_TIMEZONE='America/New_York'
      - PGID=1000
      - PUID=1000
      - TZ=America/New_York
      - SHM_SIZE=1G
    ports:
      - 1080:80
    shm_size: 1G
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - /media/4TB/Dockers/zoneminder/events:/data/zoneminder/events
      - /media/4TB/Dockers/zoneminder/images:/data/zoneminder/images
      - /media/4TB/Dockers/zoneminder/exports:/data/zoneminder/exports
      - /media/4TB/Dockers/zoneminder/sounds:/data/zoneminder/sounds
      - /media/4TB/Dockers/zoneminder/logs:/config/log/zoneminder
      - /media/4TB/Dockers/zoneminder/fonts:/usr/share/webapps/zoneminder/htdocs/skins/classic/css/fonts
      - /media/4TB/Dockers/zoneminder/config/zm-config.conf:/etc/zm/conf.d/03-remote-mysql.conf
      - /media/4TB/Dockers/zoneminder/config/php-config.ini:/etc/php/7.0/apache2/conf.d/10-myconfig.ini
```
