### ISSUE TITLE
External db

### ISSUE THREAD

**Issue by roblandry** [linuxserver/docker-zoneminder#15]
allow to connect to external db by symbolic linking /etc/zm/conf.d/03-remote-mysql.conf to host conf

Contents of 03-remote-mysql.conf
```
# ZoneMinder database hostname or ip address and optionally port or unix socket
# Acceptable formats include hostname[:port], ip_address[:port], or localhost:unix_socket
ZM_DB_HOST=192.168.x.xxx:3306

# ZoneMinder database name
ZM_DB_NAME=zm

# ZoneMinder database user
ZM_DB_USER=zmuser

# ZoneMinder database password
ZM_DB_PASS=zmpass

# SSL CA certificate for ZoneMinder database
ZM_DB_SSL_CA_CERT=

# SSL client key for ZoneMinder database
ZM_DB_SSL_CLIENT_KEY=

# SSL client cert for ZoneMinder database
ZM_DB_SSL_CLIENT_CERT=
```

My compose:
```
zoneminder:
    image: linuxserver/zoneminder
    container_name: zoneminder
    restart: always
    environment:
      - PHP_TIMEZONE='America/New_York'
      - PGID=1000
      - PUID=1000
      - TZ=America/New_York
      - SHM_SIZE=1G
    ports:
      - 1080:80
    shm_size: 1G
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - /media/4TB/Dockers/zoneminder/events:/data/zoneminder/events
      - /media/4TB/Dockers/zoneminder/images:/data/zoneminder/images
      - /media/4TB/Dockers/zoneminder/exports:/data/zoneminder/exports
      - /media/4TB/Dockers/zoneminder/sounds:/data/zoneminder/sounds
      - /media/4TB/Dockers/zoneminder/logs:/config/log/zoneminder
      - /media/4TB/Dockers/zoneminder/fonts:/usr/share/webapps/zoneminder/htdocs/skins/classic/css/fonts
      - /media/4TB/Dockers/zoneminder/config/zm-config.conf:/etc/zm/conf.d/03-remote-mysql.conf
      - /media/4TB/Dockers/zoneminder/config/php-config.ini:/etc/php/7.0/apache2/conf.d/10-myconfig.ini
```

Note:  I did have to manually create the db tables due to errors in the filters file. I can post the corrected db script if necessary.
