### ISSUE TITLE
Failed to link in web_php

### ISSUE THREAD

**Issue by roblandry** [linuxserver/docker-zoneminder#16]
I've been unable to identify this solution to this problem. Everything else working great due to previously posted issues with my workarounds. 

Errors similar to these repeat over and over...
Failed linking skins/classic/js/classic.js to skins_classic_js_classic-classic-1525472290.js

**Comment by michaelarnauts** [comment]
This is due to the ZM_CACHEDIR. The path should be `/var/cache/zoneminder`, but that doesn't exists, so zoneminder can't write to it. Also, the apache config isn't modified to allow downloading from these folders.

#13 is the the consequence of this issue.

**Comment by thelamer** [comment]
I apologize for the long delay without even a response on this, we are planning on changing massive amounts of logic for this to go live, your help with testing would be appreciated: 

https://github.com/linuxserver/docker-zoneminder/pull/21

**Comment by PX03AFK** [comment]
I know this is marked as closed but I am intrigued to know why this error is occurring when ZM is stopped.

**Comment by PX03AFK** [comment]
Also, the directory needs permissions for ZM to use it.

**Comment by PX03AFK** [comment]
What I had forgotten is that I have a cron job that periodically checks whether ZM should be running so it does a status check but doesn't, in this instance, start ZM.  So the error was presumably showing up because of the status check.

**Comment by thelamer** [comment]
The old container is dead, any problems you had with it will never get fixed. 
If you want to test the new one please see the tags to use in that PR: 

lspipepr/zoneminder:none-pkg-none-pr-21

And follow the instructions in the readme: 

https://github.com/linuxserver/docker-zoneminder/blob/alpine/README.md

Specifically use this compose example:

```
version: "3"
services:
  mariadb:
    image: linuxserver/mariadb:latest
    container_name: zoneminder_mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=dbpass
      - TZ=Europe/London
  zoneminder:
    image: lsiodev/zoneminder:latest
    container_name: zoneminder
    restart: always
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASS=dbpass
      - TZ=Europe/London
    ports:
      - "80:80"
```
